services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 321976548
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: tasks
      DB_USER: postgres
      DB_PASS: 321976548
      DB_PORT: 5432
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: >
      sh -c "ls -la && echo 'Arquivos no diretório:' && 
             find . -name '*.py' && 
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: