# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Pipeline CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi
        pip install -r requirements.txt;
               - name: Setup PostgreSQL
  # You may pin to the exact commit or the version.
  # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
    - name: setup postgresql
      uses: Harmon758/postgresql-action@v1.0.0
      with:
         # Version of PostgreSQL to use
         postgresql version: 15
         # POSTGRES_DB - name for the default database that is created
         DB_NAME: ${{ secrets.DB_NAME }}
         # POSTGRES_USER - create the specified user with superuser power
         DB_USER: ${{ secrets.DB_USER }}
         # POSTGRES_PASSWORD - superuser password
         DB_PASWORD: ${{ secrets.DB_PASWORD }}
              
